name: acuity_test_environment

services:
  postgresql:
    container_name: acuity_test_environment_postgresql
    image: postgres:16.2-bookworm
    env_file:
      - .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "logic"]
      interval: 5s
      timeout: 5s
      start_period: 20s
